"""transform to declarative style

Revision ID: 46f6c349193c
Revises: 4a7cc4db8b7e
Create Date: 2023-12-13 23:14:19.738936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46f6c349193c'
down_revision: Union[str, None] = '4a7cc4db8b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('hotels', sa.Column('image_id', sa.String(), nullable=True))
    op.alter_column('hotels', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_hotels_id'), 'hotels', ['id'], unique=False)
    op.drop_column('hotels', 'image_ig')
    op.alter_column('rooms', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('rooms', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.alter_column('rooms', 'image_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'services',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.add_column('hotels', sa.Column('image_ig', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hotels_id'), table_name='hotels')
    op.alter_column('hotels', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('hotels', 'image_id')
    op.alter_column('bookings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
